Feature/1 update arguments
semanticarts/undefined-concepts-tool pull request #7
Opened 2023-08-17 16:53 UTC by svirgilgood

* Address issue raised [here](https://github.com/semanticarts/undefined-concepts-tool/issues/1)
* Adds functionality for passing in command line files and directories for the context
* Adds functionality for passing in additional files for the focus graph
* Updates read me
* Fixes https://github.com/semanticarts/undefined-concepts-tool/issues/1

2023-08-17 17:02 UTC, e2dubba commented on README.md
> +Find all of the undefined concepts in an ontology
```suggestion
Find concepts that are referenced but undefined in an ontology.
```
@dylan-sa your summary of the function is better.

2023-08-17 18:54 UTC, rjyounes commented
@e2dubba If you add "Fixes #1" to your description, GitHub will close the issue automatically when the PR is merged.

2023-08-17 19:05 UTC, rjyounes requested changes
I haven't read through all the changes but I think there needs to be a discussion about requirements and what the functionality of this script is. I do like a lot of your coding improvements. A meeting would be useful, if Dylan would like to arrange it, but he's out until the 28th and then will be at IDA through Sept 1. So  a meeting the following week?

2023-08-17 19:05 UTC, rjyounes commented on README.md
> +TODO: This should be either created as a package, or a virtual environment to reduce the
Agreed, and you should have a requirements.txt file to state the dependencies.

2023-08-17 19:05 UTC, rjyounes commented on README.md
> +The command takes to arguments context and a focus graph. The context should include all of the
```suggestion
The command takes two arguments context and a focus graph. The context should include all of the
```

2023-08-17 19:05 UTC, rjyounes commented on README.md
> +If one does not want to include the file `bad_taxonomy.ttl`, run `./find_undefined_concepts focus_ontology_a.ttl focus_ontology_b.ttl -c ontologies/ taxonomies/taxonomyA.ttl`.
I find this complex to the point of incomprehensible. Why not keep it simple? It takes a series of arguments of files and/or folders. It will operate on each individual file, and all the files in a folder. We could save for later the idea of skipping files in a folder, but I think that's an advanced feature that isn't needed at this stage.

2023-08-17 19:05 UTC, rjyounes commented on README.md
> +Or one could run: `./find_undefined_concepts -c ontologies/ taxonomies/taxonomyA.ttl -- focus_ontology_a.ttl focus_ontology_b.ttl`.
Same comment here as above.

2023-08-17 19:05 UTC, rjyounes commented on README.md
> +Everything after the `-c` or `--context` flag is treated as an array of either files or directories. The focus graph file or files needs to appear before the flag, or after a `--`, or directly after
Same here. Note that the files where you are looking for references and the files where you are looking for definitions make up the same set of files. There is no focus other than those files.

2023-08-17 19:11 UTC, e2dubba commented on README.md
> +TODO: This should be either created as a package, or a virtual environment to reduce the
I almost added it to this PR, but if we are going to move this into a different repo, or expand the scope of the repo, it would be better to wait.

2023-08-17 19:13 UTC, e2dubba commented on README.md
> +If one does not want to include the file `bad_taxonomy.ttl`, run `./find_undefined_concepts focus_ontology_a.ttl focus_ontology_b.ttl -c ontologies/ taxonomies/taxonomyA.ttl`.
The idea is you can add directories or individual files. Its not really skipping a file, its just allowing one to pass exactly what they want.

2023-08-17 19:14 UTC, e2dubba commented on README.md
> +Everything after the `-c` or `--context` flag is treated as an array of either files or directories. The focus graph file or files needs to appear before the flag, or after a `--`, or directly after
There is though. We aren't looking for all undefined concepts in the large ontology project, just the ones that are in the specific domain ontology we are currently working with. At least, that is the scope of the current code.

2023-08-17 19:48 UTC, sa-bpelakh requested changes
I know some of these are not about this change specifically but the overall implementation. We can discuss how to address these, if you'd like.

2023-08-17 19:48 UTC, sa-bpelakh commented on README.md
> +TODO: This should be either created as a package, or a virtual environment to reduce the
`requirements.txt` is outdated for packages intended for distribution, [setuptools](https://setuptools.pypa.io/en/latest/) is the preferred route.

2023-08-17 19:48 UTC, sa-bpelakh commented on README.md
> +The script is tested with python 3.10. But most later versions of python3 should work.
Your setuptools descriptor can explicitly document the Python version dependency.

2023-08-17 19:48 UTC, sa-bpelakh commented on find_undefined_concepts.py
> +def create_defined_concepts(combined_graph):
As the code grows, using [typing](https://docs.python.org/3/library/typing.html) would make things clearer.

2023-08-17 19:48 UTC, sa-bpelakh commented on find_undefined_concepts.py
>  with open("./queries/defined_concept_query.rq", "r") as file:
Moving the queries into the module and using [importlib](https://docs.python.org/3.11/library/importlib.resources.html) to load the queries would allow the user to be able to run the tool from any directory.

2023-08-17 19:48 UTC, sa-bpelakh commented on find_undefined_concepts.py
>      undefined_concept_query_final = undefined_concept_query_template.replace("##DEFINED_CONCEPTS##", formatted_defined_concepts)
Is there a reason for the complexity of template substitution? The ontology graphs are likely quite small, and the difference is easily calculated dynamically. If you make defined_concepts a set instead of a list, you can do something like
```python
    referenced_concepts = set(
        r['referenced_concept'] for r in graph_of_interest.query(referenced_concept_query))
    undefined_concepts = referenced_concepts - defined_concepts
```

2023-08-17 19:48 UTC, sa-bpelakh commented on find_undefined_concepts.py
> +        graph_of_interest.parse(rdf_file, format=fmt)
There is no need to perform the parse twice. Instead
```python
   tmp_g = Graph()
   tmp_g.parse(rdf_file, format=fmt)
   combined_graph += tmp_g
   if graph_of_interest is not None:
     graph_of_interest += tmp_g
```

2023-08-17 19:48 UTC, sa-bpelakh commented on find_undefined_concepts.py
> +        combined_graph, graph_of_interest = add_files_to_graph(rdf_file, combined_graph, graph_of_interest)
Is the idea not to process each `focus_graph` separately? Otherwise, you will fail to flag concepts declared in sub-ontology A but referenced in sub-ontology B.

2023-08-17 19:50 UTC, rjyounes commented on README.md
> +Everything after the `-c` or `--context` flag is treated as an array of either files or directories. The focus graph file or files needs to appear before the flag, or after a `--`, or directly after
Hm, OK, that's not what I thought it was doing.

2023-08-17 19:52 UTC, rjyounes commented on README.md
> +If one does not want to include the file `bad_taxonomy.ttl`, run `./find_undefined_concepts focus_ontology_a.ttl focus_ontology_b.ttl -c ontologies/ taxonomies/taxonomyA.ttl`.
OK, I must have misunderstood what you are doing. That is the required functionality.

2024-03-26 13:50 UTC, rjyounes commented
This repository is being archived because it is not an all-purpose script, so closing this PR.

2024-03-26 13:50 UTC, closed without merging